"""Which texture fetch slots each converted shader reads, from XenosRecomp's HLSL.

The native renderer binds a texture for every valid fetch constant unless it
knows the slots a draw's shaders use. XenosRecomp names each sampler slot with
defines like

    #define sampDiffuse_Texture2DDescriptorIndex vk::RawBufferLoad<uint>(g_PushConstants.SharedConstants + 20)

(offset / 4 = dimension * 32 + slot), and the shader body refers to those
names. This writes cache/shader-native/fetch_slots.cpp: one entry per shader
with the FNV-1a hash in its file name (the one --svr_shader_dump_dir uses) and
a 32-bit mask of the slots its body references. Game-derived output, never
committed.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SLOTS = 32
ALL_SLOTS = (1 << SLOTS) - 1

DEFINE = re.compile(
    r"^#define (\w+)_(?:Texture\w+|Sampler)DescriptorIndex "
    r"vk::RawBufferLoad<uint>\(g_PushConstants\.SharedConstants \+ (\d+)\)",
    re.MULTILINE,
)
REFERENCE = re.compile(r"\b(\w+)_(?:Texture(?:2D|3D|Cube)|Sampler)DescriptorIndex\b")
FILE_NAME = re.compile(r"^(?:ps|vs)_([0-9a-f]{16})\.hlsl$")


def slot_mask(hlsl: str) -> int:
    """Mask of the fetch slots the shader body uses; all slots if unsure."""
    slots: dict[str, int] = {}
    for name, offset in DEFINE.findall(hlsl):
        slots[name] = (int(offset) // 4) % SLOTS
    mask = 0
    for line in hlsl.splitlines():
        stripped = line.strip()
        if stripped.startswith("#define") or "packoffset" in stripped:
            continue
        for name in REFERENCE.findall(line):
            if name not in slots:
                return ALL_SLOTS
            mask |= 1 << slots[name]
    return mask


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Write the fetch slots each converted shader reads.")
    parser.add_argument("hlsl_dir", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args(argv)

    entries = []
    for path in sorted(args.hlsl_dir.glob("*.hlsl")):
        match = FILE_NAME.match(path.name)
        if not match:
            continue
        mask = slot_mask(path.read_text(encoding="utf-8", errors="replace"))
        entries.append((int(match.group(1), 16), mask))
    entries.sort()

    lines = [
        "// Generated by scripts/shader_fetch_slots.py from XenosRecomp's HLSL; do not edit.",
        '#include "native/shader_cache.h"',
        "",
        "const ShaderFetchSlots g_shaderFetchSlots[] = {",
    ]
    lines += [f"    {{0x{fnv:016x}ull, 0x{mask:08x}u}}," for fnv, mask in entries]
    if not entries:
        lines.append("    {0, 0},")
    lines += [
        "};",
        f"const size_t g_shaderFetchSlotCount = {len(entries)};",
        "",
    ]
    args.output.write_text("\n".join(lines), encoding="utf-8")
    unsure = sum(1 for _, mask in entries if mask == ALL_SLOTS)
    print(f"{len(entries)} shaders, {unsure} bind every slot: {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
